apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:p3dcajnrOMmMm3wvqFvIXUNQeoOAgHQNtyjhOTApNGV03TwB,iv:FWhr0/5mLiDtVZq8cPeUDsNQc/1C4rQ4vAtJmiXgqZk=,tag:5vdkKBg//hyK8DYmo024CQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:FWfedAXHZPyUx+fxp3nD0MR2E/0KrWXh1WouzWJQQkSD4FGo/Lf71aOqQtAHvb+aX/BFc1VqSGl/9HV44rJYj63X2JjzdZf5LpA/dTdcUYUx3XX/wz4uc4Skt4d5J6lAGQ2ReMJqRFIZ8lKVd9crHeefEMEej/aaHV6ILtCVjeqFYFWmsXFfYvj14PEcQfYXHLD8wEaIDFZ0p9bN//1ZpRV/mLCzlf9Qab/d48PGPg==,iv:5jTa3ZAoa9g4TNIcUhtRc5zDD2OilNeB1atzeJt47C4=,tag:RcmkKbKsT/QcjnJVxpGdng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SkxBY200RlQ2eWJlVThY
            ZGFnQVVPbzNQdFRMRjZsa0FsY2ttQjNMZGxJClR5RmZvaXo5WGRIZElRUXNicUZF
            bUdoMzJ3WVQ4QzFVSTVMSW0vL1E3NzgKLS0tIGd6U3Y1ZDdMU2hXZHR3SWpKcnY2
            VW02dk10RWkxVXFKNnpsQjRRRzNCN0UKwUBOVb+iuEZx9ee0STN+c2wuwHpeqQ6t
            gOdmjharreYmzDRRo1nAxsOAyrjDspspb5gxoEqRhUzZUf8B7EcxQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T00:28:15Z"
    mac: ENC[AES256_GCM,data:dLzNsC0VxzpjlqQz3jJEboP5vShsfK75P0zCvS0BhySvRF5pPMwKuT3PNFKx6WubFAO9ZH5RPG4XU3Xek3CEGYUVpZRAuoR/RZ5HkqaIhVZkKiNtrc2TMgoc71Qy5fI7zCzcHfWIGbTKkaJCpydAAvkfRHQdr+P4/z0B8TmsZiU=,iv:LQVraRuLIzCsQasQW1Ge6NlkS8bfMWcg4jJj29JwG3g=,tag:WCpYTP3J3/KYASvQNTcmuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
