apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9WhgLN9GkuzDScXY6W+8eB/1noKMP9Rzkt2hJGLxJFtPQAOG,iv:b+RuSYUX8E4fLuP4L7Hk8IqajpjhZ9ZHIvv4RV2btNY=,tag:5+MOWmwqd6SGIdzxGCa0AA==,type:str]
    credentials.json: ENC[AES256_GCM,data:XkV1hKbfrtFrP3sB40oNbQdWGLYcfi7jWKav+FJxgcrXF+0u33FyosCLwbBiN5NMdGi5DnoPP/7dvGF687C8AFqDVWHYRvRsormZAZOfLvtRHxo+855l49o2SQxNvcDKOXaANuIgJ03yoBG0/rO0FJtVgFwgtY8yzKBN7SkloHZpXRdEvURukG4COLgKLwyuWP8csA0w1XYlukUUl1OvdMiirmfW94DTItQxDJuXuQ==,iv:7i1KSVN58LPTeIdkic2br+F0dzGn6ZC9f+Jhc+pgXMY=,tag:E54ngJgq31OiIMK46qHPww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNejlBalZweWUwWWlnYk5w
            Mk9LNnMwUm1PWExteXhONGhTMitzYll1cFJZCmVxRy9abjgvZTVwNDdBUTFzWk8y
            cDdxK2Z0YkNDc0ZVT0FkOE9rZ0h6QVEKLS0tIElYSFIvSHRXVmVZYnE2YVdQeG95
            aUFrRHVNUXpnektVZFYrdExXNlo4U2cKn0SBJ9KmJbz9wyTQS/9NujMqhGmQrAtQ
            MeNuKehYQHpGPmKEjttUEUnA5xOBUMEWIF8eiy+ptCC5OFyBrL1MCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T00:41:09Z"
    mac: ENC[AES256_GCM,data:sYQ2TVvpqYB/V95a0Wt9TN1w4cuJygqPwQKLPCK2AAqO8UOcIoFQAp5YO2Vk4kCtBN3J1kNTgfJ0dIMJOqSNVCx82QHcFWhR7iDHYU1IIGMU/fV/DxTn4/qB1uWub3TyxxAVL+KHS6e9Wge/KsieIjLbiCrybSYjRaWHoxRZjqE=,iv:tLInL+DYGlurXwJPkc4qE3orwsOsCQnRoGQzc7RcjCM=,tag:w3sU6/imcnBzljW3OEgQEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
