---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Gi