apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
type: Opaque
stringData:
    values.yaml: |
        postgresql:
          postgresqlPassword: Yj1cWAmX7oITV2NbEd+zHqUpEiJI8k6pLGkJS5ZcOdmdT98n
        authentik:
          secret_key: nuZP2Pl6g3LmIum4fV8eI4inn0RoeT23pAgtemuLENwMcRNP 
          postgresql:
            password: WjEgpi2VkgtNBc/J+5p8y5hP8OdxNfpKQjcTx8fZ80vx3FLf
          