apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:nxsKExwSVYvfpsOpsBGGA37uU8OdEqn4FEaAnYZL4s8EXX3Hm2jYcPZDZ+fHuyXBgmMwLnkj0L065XjUaF83JXZ+CZx50ki24dimZnNSlopD2m2ViKiRdYUmO72UciCIAL3cf/Cyl5u/aDDtABfupOv0g+XhbsPyVIP3eVi05XYx4eIi+Li9r3RyZFnQ3BbBdnnIPv9rHz+j5AhKmRS1iRgOZkeEa1qkzal9SKpNppkT+7/9LuAmhdlewsu+ZDwC7VHapHUJPn8sPCcULnP3C9W99/y4WGRQf0pyp0VGF89OIhDBV3t2Qa+JVpbH,iv:/IPOIwq8sfDEOATmzQYsEKdBPuaKCqhytdxd6ZcZnLM=,tag:CJSADUDTM075JHlB//zOsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkdOdWwyMzNzQlRyNzZs
            QThjRU9VbjdNZHdSQzUrR3M2NUkwOXJ4akVBCmtHczdxYzZTSTNYTVRydHFTbWFk
            Q0xDdzlTa3Z5c1h1RDVTbk5lYzBhbWsKLS0tIHE5a3ZrZVhFWWppUFppQ1RDZ1hX
            aTg1SkNCTUhlbXhLRWtCOERMZmlCVlkKs6vrSzZK1BMVbb0fTbnJgj8rlSQ/e6mV
            vQmNWV2PzZs2jTodNGq/GaGEH9gGbkcWTelDcivo7ae9Wd6qCg7bpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-05T08:23:05Z"
    mac: ENC[AES256_GCM,data:mUC8YVgHDy2qrWTiztqs2L7eCu7yxb7tM6NbkwT0aS7pvEW/xeTiU5jvgHrYPBq/6/Ff+DygZF2kdUwNJgAzjY7ax5mIlIxEQSCZt2b/dlGVw1DeD6XDNgNaFyRAgIsQTqFhX7JbF8rucfndBBicU335cvuvGYQkz7xv43nEU+k=,iv:iO9tBjg4Ip/JaR5QxLLyRJcqh0cXgAnO85HUDl9SSMI=,tag:6TMY62CKiPfJEd7nsuAcIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
