apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:NqesN5yRj56BNeXGZ9GDU6U+v3zpt+N0egs35j080o0fNuICBmVJcw==,iv:X2k5/Yzi0wv6NJnNsBMp6PnjBTQjN7VCWS5XJH1z8TU=,tag:8wdWhJ5toJNDKE9nFXg7Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWC8zMEZCWWJJZUdoMHJU
            alpuWk5kQjdDdXFqWWFLQlRIdi9JbnRqTEYwClBLc2tZeWZEdkRqT1pEK2hjNTR2
            c1JuVHNKTEdHc3ZEV2VkZnUrWTVoalEKLS0tIGNITytiWXpEMzA0WmYvQWU1SEtX
            d3BNNlR6M3lMdExCSDk0dFFXT2JhelEKcMYSYSAerDHwAM7+tBxQRlWVXj6i/Y2S
            jPU2CA4kzeWx6uzDV+h+PoQD+XvNcSXOoru0KZVJC5Ma5LHtQP+/BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T07:13:47Z"
    mac: ENC[AES256_GCM,data:FJl2EiHo1IdcCNscn7B5zhkGFrWJRpGITshJnhUryktousAHqAurRPXWy5sNDpN9JZ4b0+r96kVF0MU6ocCrTswjUgS2dgO3RVA5vhhjbl2r9gFFFPWtOyVEgNYjPVhbFEACDu+8Olqva7bMGc8RlRayhdjAtzbCzKYV5XEx7Fo=,iv:QNX40SDwWTLmu+IaUw0S8Jln8bZ8SFePS/cMgQ6IVeM=,tag:qFXlhfDR7Zu3yRhIBJurBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
