apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:YDlDGeAO/WBp8P/y/VlZVDWBS7HKMHaGo4GYzsRO6B8=,iv:aIyhXZV1FTP7CeAnVqIVEzcjuvKSM0eEmazhgKjB5Mg=,tag:SIpuogKnpvCZB6y0wHZVEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSHdqUFNhVEthbncxNkNt
            NWlvdzFJUzEyam5YcTQ5ZjJ3bHdSeWgrYTNNCnlIU3lLOElrcERJTWsybDZRNzBj
            TW1CZ29COXBUclF1RC9tNW4xK0FsNzgKLS0tIGVJMVUzWmxBZTg5OTBPMFNsZ1la
            QmhQYkFwamJxSi9JQXJzVXl0aW9IcG8KsBvVJxVBOB3JM9Jug45wyKgRsDFkRAsC
            /JSijThQCJ5qfI8HPyim/uXGaTpW6Rjtd02QLiRfnVp+X2gKD6zXsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T07:46:57Z"
    mac: ENC[AES256_GCM,data:ltNOT4va8v9ezKf2AImF//yvdRFo3BXCYd3GoCFQ6usoY8dkXQzB844PT1Y79vcjNjDW2m+LEPeEcZxrXyjZ0anZrH63ufqPe1vwRXcNPJlSuM5M8g/q6fNzATNTYlu/wHm+OFEfUWLKJxFuSY0mj0KeRucYCq1pbaTHb7c08Uo=,iv:K/P7SCRA3KlKqU69kKJz1FgXrTaEBj+Svvbtc8qYt78=,tag:wFsPEEjW1d9HgQJHA8zF4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
