apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:sG/5UG5hGX8GYMBhNxVlkzNYG5x6gE+PT/T7YqTJRv5u1y47SBbGaQ==,iv:JjxkVBDQQlUo0aRgNaue3S/sGGUMgEHuth6pAfcWSa4=,tag:FXtdCux1hwHeMQ5cWaxTFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMU43WjZJZlpzVVlYcUNB
            OG40VXl6TUF3VmpWODViK2pDdU5vR2ZRMVZJCk5QZkhXZ202Z2t3Tld3YjI3b0RE
            alJkZ0NUUTNXNWR3b3FUWHUyMlozRDQKLS0tIEFnMWlGQk1FZXdFU3V4K3pzY0l2
            cC9UVFR6VE1YL2xZTnBPS0x3aDZxT2cK8A7h484/QL4mC/qYlRLGV5R7nGNKo120
            QtJtPGhT3Zf4D35bmpsaJhmpgwooIviJ/br/xuijWA0j6SPmo4zJ5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T23:06:17Z"
    mac: ENC[AES256_GCM,data:IOLcNAoAKQn7bZGxP93nPcz0yqqnPVQ3K5ijcF4i8j++FX8wqzFTE82gMlDNA415sxxZZoMdJmHyBl9iFpuLAdfVqJWkHud45VyuhgaWSHePo6rfmweeNMcHXfp80MeVmrWwowYT++faXBPR1KLBhp8bBQr99WAzskQk9RQ4IlI=,iv:6pOve9rzWBvGJcP5fbZJjaol1DRnXBR/9BAY3XxDiKs=,tag:3xtqzbhklFznztAP7JzNsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
